openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: This is an example API schema for demonstrating CRUD operations.

servers:
  - url: https://api.example.com
    description: The base URL for the API.

paths:
  /resources:
    get:
      operationId: fetchSomeResources
      summary: Fetch a list of resources
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            format: int32
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: A list of resources
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int32
                    name:
                      type: string
                    description:
                      type: string

    post:
      operationId: createSomeResource
      summary: Create a new resource
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
        required: true
      responses:
        "201":
          description: The created resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  description:
                    type: string

  /resources/{resourceId}:
    put:
      operationId: updateSomeResource
      summary: Update an existing resource
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
        required: true
      responses:
        "200":
          description: The updated resource
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    format: int32
                  name:
                    type: string
                  description:
                    type: string

    delete:
      operationId: deleteSomeResource
      summary: Delete a resource
      parameters:
        - name: resourceId
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        "204":
          description: Resource deleted successfully
