name: api_client_generator
version: 0.1.2
description: A Dart package to generate API client code from an OpenAPI schema.
repository: https://github.com/KaungKhantKyaw1997/api_client_generator
homepage: https://github.com/KaungKhantKyaw1997/api_client_generator#readme

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  http: ^1.2.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.7

topics:
  - api
  - client
  - generator
  - openapi
  - code-generation
